---
stacks:
  cflinuxfs3:
    tag: full
  bionic:
    tag: base
  tiny:
    tag: tiny
builders:
  tiny:
    stack: tiny
    version-key: tiny
    repository: cloudfoundry/cnb
    builder-image-params:
      REPO: cloudfoundry/cnb
      STACK: "org.cloudfoundry.stacks.tiny"
      BUILD_IMAGE: "cloudfoundry/build:tiny-cnb"
      RUN_IMAGE: "cloudfoundry/run:tiny-cnb"
      HOST: "hub.docker.com"
  bionic:
    stack: bionic
    version-key: bionic
    repository: cloudfoundry/cnb
    builder-image-params:
      REPO: cloudfoundry/cnb
      STACK: "io.buildpacks.stacks.bionic"
      BUILD_IMAGE: "cloudfoundry/build:base-cnb"
      RUN_IMAGE: "cloudfoundry/run:base-cnb"
      HOST: "hub.docker.com"
  cflinuxfs3:
    stack: cflinuxfs3
    version-key: cflinuxfs3
    repository: cloudfoundry/cnb
    latest: true
    builder-image-params:
      REPO: cloudfoundry/cnb
      STACK: "org.cloudfoundry.stacks.cflinuxfs3"
      BUILD_IMAGE: "cloudfoundry/build:full-cnb"
      RUN_IMAGE: "cloudfoundry/run:full-cnb"
      HOST: "hub.docker.com"
cnbs:
  nodejs:
    git_owner: "cloudfoundry"
    git_repo: "nodejs-cnb"
    skip_stack:
      - "tiny"
  python:
    git_owner: "cloudfoundry"
    git_repo: "python-cnb"
    skip_stack:
      - "bionic"
      - "tiny"
  go:
    git_owner: "cloudfoundry"
    git_repo: "go-cnb"
  httpd:
    git_owner: "cloudfoundry"
    git_repo: "httpd-cnb"
    skip_stack:
      - "bionic"
      - "tiny"
  nginx:
    git_owner: "cloudfoundry"
    git_repo: "nginx-cnb"
    skip_stack:
      - "bionic"
      - "tiny"
  php:
    git_owner: "cloudfoundry"
    git_repo: "php-cnb"
    skip_stack:
      - "bionic"
      - "tiny"
  openjdk:
    git_owner: "cloudfoundry"
    git_repo: "openjdk-cnb"
    skip_stack:
      - "tiny"
  buildsystem:
    git_owner: "cloudfoundry"
    git_repo: "build-system-cnb"
    skip_stack:
      - "tiny"
  jvmapplication:
    git_owner: "cloudfoundry"
    git_repo: "jvm-application-cnb"
    skip_stack:
      - "tiny"
  azureapplicationinsights:
    git_owner: "cloudfoundry"
    git_repo: "azure-application-insights-cnb"
    skip_stack:
      - "tiny"
  debug:
    git_owner: "cloudfoundry"
    git_repo: "debug-cnb"
    skip_stack:
      - "tiny"
  googlestackdriver:
    git_owner: "cloudfoundry"
    git_repo: "google-stackdriver-cnb"
    skip_stack:
      - "tiny"
  jmx:
    git_owner: "cloudfoundry"
    git_repo: "jmx-cnb"
    skip_stack:
      - "tiny"
  procfile:
    git_owner: "cloudfoundry"
    git_repo: "procfile-cnb"
    skip_stack:
      - "tiny"
  dotnet-core:
    git_owner: "cloudfoundry"
    git_repo: "dotnet-core-cnb"
    skip_stack:
      - "tiny"
  archiveexpanding:
    git_owner: "cloudfoundry"
    git_repo: "archive-expanding-cnb"
    skip_stack:
      - "tiny"
  tomcat:
    git_owner: "cloudfoundry"
    git_repo: "tomcat-cnb"
    skip_stack:
      - "tiny"
  jdbc:
    git_owner: "cloudfoundry"
    git_repo: "jdbc-cnb"
    skip_stack:
      - "tiny"
  springautoreconfiguration:
    git_owner: "cloudfoundry"
    git_repo: "spring-auto-reconfiguration-cnb"
    skip_stack:
      - "tiny"
  springboot:
    git_owner: "cloudfoundry"
    git_repo: "spring-boot-cnb"
    skip_stack:
      - "tiny"
  distzip:
    git_owner: "cloudfoundry"
    git_repo: "dist-zip-cnb"
    skip_stack:
      - "tiny"
