#@ languages = ["apt", "binary", "dotnet-core", "go", "nodejs", "python", "ruby", "staticfile", "php", "nginx"]
#@ stacks = {
#@   "apt": ["cflinuxfs3"],
#@   "binary": ["cflinuxfs3", "windows2012R2", "windows2016"],
#@   "dotnet-core": ["cflinuxfs3"],
#@   "go": ["cflinuxfs3"],
#@   "multi": ["cflinuxfs3"],
#@   "nginx": ["cflinuxfs3"],
#@   "nodejs": ["cflinuxfs3"],
#@   "php": ["cflinuxfs3"],
#@   "python": ["cflinuxfs3"],
#@   "ruby": ["cflinuxfs3"],
#@   "staticfile": ["cflinuxfs3"],
#@   "java": ["cflinuxfs3"]
#@ }
#@ pas_versions= {
#@   "latest": "2_6",
#@   "n-1": "2_5",
#@   "n-2": "2_4",
#@ }
#@ lts = pas_versions["n-2"]
#@yaml/text-templated-strings
---
resource_types:
  - name: cron
    type: docker-image
    source:
      repository: cfbuildpacks/cron-resource
  - name: cf-space-resource
    type: docker-image
    source:
      repository: cfbuildpacks/cf-space-resource
  - name: pcf-pool
    type: docker-image
    source:
      repository: cftoolsmiths/toolsmiths-envs-resource

resources:
  - name: nightly-trigger
    type: cron
    source:
      expression: 0 6 * * *
      location: ((current-timezone))

  - name: buildpacks-ci
    type: git
    source:
      uri: ((buildpacks-ci-git-uri-public))
      branch: ((buildpacks-ci-git-uri-public-branch))

  - name: edge-environments
    type: pool
    source:
      branch: master
      pool: edge-environments
      private_key: ((public-buildpacks-ci-robots-private-key))
      uri: git@github.com:cloudfoundry/public-buildpacks-ci-robots

  - name: lts-environments
    type: pool
    source:
      branch: master
      pool: lts-environments
      private_key: ((public-buildpacks-ci-robots-private-key))
      uri: git@github.com:cloudfoundry/public-buildpacks-ci-robots

  - name: env-repo
    type: git
    source:
      uri: git@github.com:cloudfoundry/buildpacks-envs
      branch: master
      private_key: ((buildpacks-envs-private-key))

  - name: buildpack-packager
    type: github-release
    source:
      user: ((buildpacks-github-org))
      repository: buildpack-packager
      access_token: ((buildpacks-github-token))

  - name: "smith-environments-(@= lts @)"
    type: pcf-pool
    source:
      api_token: ((toolsmiths-api-token))
      hostname: environments.toolsmiths.cf-app.com
      pool_name: "us_(@= lts @)"
    tags:
    - buildpacks-eng-vsphere

#@ for language in languages:
  - name: "buildpack-(@= language @)"
    type: git
    webhook_token: ob0aigh3
    source:
      uri: "git@github.com:cloudfoundry/(@= language @)-buildpack.git"
      private_key: "(((@= language @)-buildpack-private-key))"
      branch: master
#@ end

jobs:
#@ for language in languages:
  - name: "brats-(@= language @)-lts"
    serial: true
    public: true
    plan:
      - in_parallel:
        - put: lts-environments
          params:
            acquire: true
        - get: buildpacks-ci
        - get: buildpack
          resource: "buildpack-(@= language @)"
        - get: nightly-trigger
          trigger: true
      - do:
        - put: "smith-environments-(@= lts @)"
          params:
            action: claim
          tags:
          - buildpacks-eng-vsphere
        - task: create-cf-space
          file: buildpacks-ci/tasks/create-cf-space-toolsmiths/task.yml
          input_mapping:
            environment: "smith-environments-(@= lts @)"
          params:
            ORG: pivotal
        - task: run-brats-cflinuxfs3
          file: buildpacks-ci/tasks/run-bp-brats/task.yml
          attempts: #@ 3 if language == "ruby" else 1
          params:
            CF_STACK: cflinuxfs3
            GINKGO_ATTEMPTS: 4
            GINKGO_NODES: 6
        ensure:
          in_parallel:
          - put: "smith-environments-(@= lts @)"
            params:
              action: unclaim
              env_file: "smith-environments-(@= lts @)/metadata"
            tags:
            - buildpacks-eng-vsphere
          - put: lts-environments
            params:
              release: lts-environments
  - name: "brats-(@= language @)-edge"
    serial: true
    public: true
    plan:
      - in_parallel:
        - put: edge-environments
          params:
            acquire: true
        - get: buildpacks-ci
        - get: env-repo
        - get: buildpack
          resource: "buildpack-(@= language @)"
        - get: nightly-trigger
          trigger: true
      - in_parallel:
  #@ for stack in stacks[language]:
        - do:
          - task: create-cf-space
            attempts: 3
            file: buildpacks-ci/tasks/create-cf-space/task.yml
            output_mapping: {cf-space: "cf-space-(@= stack @)" }
            params:
              ENV_POOL_RESOURCE: edge-environments
              ENVS_DIR: env-repo
              ORG: pivotal
              SYSTEM_DOMAIN: builldpacks-gcp.ci.cf-app.com
              USERNAME: admin
          - task: run-brats-#@ stack
            file: buildpacks-ci/tasks/run-bp-brats/task.yml
            input_mapping: {cf-space: "cf-space-(@= stack @)" }
            params:
              CF_STACK: #@ stack
              GINKGO_ATTEMPTS: 4
              GINKGO_NODES: 6
            ensure:
              task: delete-cf-space
              file: buildpacks-ci/tasks/delete-cf-space/task.yml
              input_mapping: {cf-space: "cf-space-(@= stack @)" }
  #@ end
    ensure:
      put: edge-environments
      params:
        release: edge-environments
#@ end

  - name: update-buildpack-packager
    serial: true
    public: true
    plan:
      - in_parallel:
        - get: buildpacks-ci
        - get: gem
          resource: buildpack-packager
          trigger: true
        - get: repo-with-gemfile
          resource: brats
      - task: update-buildpack-packager
        file: buildpacks-ci/tasks/update-gem-in-gemfile/task.yml
        params:
          RUBYGEM_MIRROR: ((rubygem-mirror))
          GEM_NAME: buildpack-packager
          GEM_GIT_REPOSITORY: ((buildpack-packager-git-uri-public))
          GEMFILE_NAME: Gemfile
      - put: brats
        params:
          repository: repo-with-gemfile-artifacts
          rebase: true
