resources:
- name: buildpacks-ci
  type: git
  source:
    uri: '{{buildpacks-ci-git-uri-public}}'
    branch: master
- name: cnb-builder
  type: git
  source:
    uri: https://github.com/cloudfoundry/cnb-builder
    branch: master
- name: p-cnb-builder
  type: git
  source:
    uri: git@github.com:pivotal-cf/p-cnb-builder
    private_key: '{{cf-buildpacks-eng-github-ssh-key}}'
    branch: master
- name: new-cves
  type: git
  source:
    uri: git@github.com:cloudfoundry/public-buildpacks-ci-robots
    branch: master
    paths:
    - new-cve-notifications/ubuntu18.04-tiny.yml
    private_key: '{{public-buildpacks-ci-robots-private-key}}'
- name: packager
  type: git
  source:
    uri: https://github.com/cloudfoundry/libcfbuildpack
    branch: master
- name: pack-release
  type: github-release
  source:
    user: buildpack
    repository: pack
    access_token: '{{buildpacks-github-token}}'
    globs:
    - '*-linux.tgz'
- name: cnb-lifecycle-release
  type: github-release
  source:
    repository: lifecycle
    user: buildpack
    access_token: '{{buildpacks-github-token}}'
- name: cflinuxfs3-run-cnb-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/stacks
    branch: master
    paths:
    - cflinuxfs3/cnb/run/**
- name: bionic-run-base-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/stacks
    branch: master
    paths:
    - bionic/base/run/**
- name: bionic-run-cnb-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/stacks
    branch: master
    paths:
    - bionic/cnb/run/**
- name: cflinuxfs3-build-cnb-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/stacks
    branch: master
    paths:
    - cflinuxfs3/cnb/build/**
- name: bionic-build-base-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/stacks
    branch: master
    paths:
    - bionic/base/build/**
- name: bionic-build-cnb-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/stacks
    branch: master
    paths:
    - bionic/cnb/build/**
- name: tiny-run-base-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/stacks
    branch: master
    paths:
    - tiny/base/*
- name: tiny-run-cnb-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/stacks
    branch: master
    paths:
    - tiny/cnb/*
- name: cflinuxfs3-version
  type: semver
  source:
    initial_version: 0.0.1
    bucket: cnb-versions
    key: builder/cflinuxfs3
    access_key_id: '{{pivotal-offline-buildpacks-s3-access-key}}'
    secret_access_key: '{{pivotal-offline-buildpacks-s3-secret-key}}'
- name: cflinuxfs3-piv-version
  type: semver
  source:
    initial_version: 0.0.1
    bucket: cnb-versions
    key: builder/cflinuxfs3-piv
    access_key_id: '{{pivotal-offline-buildpacks-s3-access-key}}'
    secret_access_key: '{{pivotal-offline-buildpacks-s3-secret-key}}'
- name: bionic-version
  type: semver
  source:
    initial_version: 0.0.1
    bucket: cnb-versions
    key: builder/bionic
    access_key_id: '{{pivotal-offline-buildpacks-s3-access-key}}'
    secret_access_key: '{{pivotal-offline-buildpacks-s3-secret-key}}'
- name: bionic-piv-version
  type: semver
  source:
    initial_version: 0.0.1
    bucket: cnb-versions
    key: builder/bionic-piv
    access_key_id: '{{pivotal-offline-buildpacks-s3-access-key}}'
    secret_access_key: '{{pivotal-offline-buildpacks-s3-secret-key}}'
- name: tiny-version
  type: semver
  source:
    initial_version: 0.0.1
    bucket: cnb-versions
    key: builder/tiny
    access_key_id: '{{pivotal-offline-buildpacks-s3-access-key}}'
    secret_access_key: '{{pivotal-offline-buildpacks-s3-secret-key}}'
- name: builder-image
  type: docker-image
  source:
    email: cf-buildpacks-eng@pivotal.io
    username: '{{buildpacks-docker-username}}'
    password: '{{buildpacks-docker-password}}'
    repository: cloudfoundry/cnb
- name: pivotal-builder-image
  type: docker-image
  source:
    repository: gcr.io:443/cf-buildpacks/p-cnb-builder
    username: _json_key
    password: '{{gcp-service-account-key}}'
- name: bionic-run-base-image
  type: docker-image
  source:
    repository: cloudfoundry/run
    tag: base
    username: '{{buildpacks-docker-username}}'
    password: '{{buildpacks-docker-password}}'
    email: cf-buildpacks-eng@pivotal.io
- name: bionic-run-cnb-image
  type: docker-image
  source:
    repository: cloudfoundry/run
    tag: base-cnb
    username: '{{buildpacks-docker-username}}'
    password: '{{buildpacks-docker-password}}'
    email: cf-buildpacks-eng@pivotal.io
- name: cflinuxfs3-run-base-image
  type: docker-image
  source:
    repository: cloudfoundry/run
    tag: full
    username: '{{buildpacks-docker-username}}'
    password: '{{buildpacks-docker-password}}'
    email: cf-buildpacks-eng@pivotal.io
- name: cflinuxfs3-run-cnb-image
  type: docker-image
  source:
    repository: cloudfoundry/run
    tag: full-cnb
    email: '{{buildpacks-docker-user-email}}'
    username: '{{buildpacks-docker-username}}'
    password: '{{buildpacks-docker-password}}'
- name: bionic-build-base-image
  type: docker-image
  source:
    repository: cloudfoundry/build
    tag: base
    username: '{{buildpacks-docker-username}}'
    password: '{{buildpacks-docker-password}}'
    email: cf-buildpacks-eng@pivotal.io
- name: bionic-build-cnb-image
  type: docker-image
  source:
    repository: cloudfoundry/build
    tag: base-cnb
    username: '{{buildpacks-docker-username}}'
    password: '{{buildpacks-docker-password}}'
    email: cf-buildpacks-eng@pivotal.io
- name: cflinuxfs3-build-base-image
  type: docker-image
  source:
    repository: cloudfoundry/build
    tag: full
    username: '{{buildpacks-docker-username}}'
    password: '{{buildpacks-docker-password}}'
    email: cf-buildpacks-eng@pivotal.io
- name: cflinuxfs3-build-cnb-image
  type: docker-image
  source:
    repository: cloudfoundry/build
    tag: full-cnb
    email: '{{buildpacks-docker-user-email}}'
    username: '{{buildpacks-docker-username}}'
    password: '{{buildpacks-docker-password}}'
- name: tiny-run-base-image
  type: docker-image
  source:
    repository: cloudfoundry/run
    tag: tiny
    email: '{{buildpacks-docker-user-email}}'
    username: '{{buildpacks-docker-username}}'
    password: '{{buildpacks-docker-password}}'
- name: tiny-run-cnb-image
  type: docker-image
  source:
    repository: cloudfoundry/run
    tag: tiny-cnb
    email: '{{buildpacks-docker-user-email}}'
    username: '{{buildpacks-docker-username}}'
    password: '{{buildpacks-docker-password}}'
- name: tiny-build-cnb-image
  type: docker-image
  source:
    repository: cloudfoundry/build
    tag: tiny-cnb
    email: '{{buildpacks-docker-user-email}}'
    username: '{{buildpacks-docker-username}}'
    password: '{{buildpacks-docker-password}}'
jobs:
- name: test-tiny
  plan:
  - get: tiny-run-base-dockerfile
    trigger: true
  - get: buildpacks-ci
  - get: new-cves
    trigger: true
  - task: integration-test
    privileged: true
    file: buildpacks-ci/tasks/test-tiny-docker-image/task.yml
- name: update-tiny-base-image
  public: true
  plan:
  - get: tiny-run-base-dockerfile
    passed:
    - test-tiny
    trigger: true
  - get: new-cves
    passed:
    - test-tiny
    trigger: true
  - put: tiny-run-base-image
    params:
      build: tiny-run-base-dockerfile/tiny/base/run
      build_args:
        squash: squash
    attempts: 2
- name: update-tiny-run-cnb-image
  public: true
  plan:
  - get: tiny-run-cnb-dockerfile
    trigger: true
  - get: tiny-run-base-image
    passed:
    - update-tiny-base-image
    trigger: true
  - put: tiny-run-cnb-image
    params:
      build: tiny-run-cnb-dockerfile/tiny/cnb/run
      build_args:
        base_image: cloudfoundry/run:tiny
        squash: squash
    attempts: 2
- name: update-tiny-build-cnb-image
  public: true
  plan:
  - get: bionic-build-cnb-dockerfile
    trigger: true
  - get: bionic-build-base-image
    trigger: true
    passed:
    - update-bionic-build-base-image
  - put: tiny-build-cnb-image
    params:
      build: bionic-build-cnb-dockerfile/bionic/cnb/build
      build_args:
        base_image: cloudfoundry/build:base
        stack_id: org.cloudfoundry.stacks.tiny
        squash: squash
    attempts: 2
- name: update-cflinuxfs3-run-cnb-image
  public: true
  plan:
  - get: cflinuxfs3-run-cnb-dockerfile
    trigger: true
  - get: cflinuxfs3-run-base-image
    trigger: true
  - put: cflinuxfs3-run-cnb-image
    params:
      build: cflinuxfs3-run-cnb-dockerfile/cflinuxfs3/cnb/run
      build_args:
        base_image: cloudfoundry/run:full
        squash: squash
    attempts: 2
- name: update-bionic-run-base-image
  public: true
  plan:
  - get: bionic-run-base-dockerfile
    trigger: true
  - put: bionic-run-base-image
    params:
      build: bionic-run-base-dockerfile/bionic/base/run
      build_args:
        squash: squash
      attempts: 2
- name: update-bionic-run-cnb-image
  public: true
  plan:
  - get: bionic-run-cnb-dockerfile
    trigger: true"
  - get: bionic-run-base-image
    trigger: true
    passed:
    - update-bionic-run-base-image
  - put: bionic-run-cnb-image
    params:
      build: bionic-run-cnb-dockerfile/bionic/cnb/run
      build_args:
        base_image: cloudfoundry/run:base
        squash: squash
      attempts: 2
      tag_as_latest: true
- name: update-cflinuxfs3-build-cnb-image
  public: true
  plan:
  - get: cflinuxfs3-build-cnb-dockerfile
    trigger: true
  - get: cflinuxfs3-build-base-image
    trigger: true
  - put: cflinuxfs3-build-cnb-image
    params:
      build: cflinuxfs3-build-cnb-dockerfile/cflinuxfs3/cnb/build
      build_args:
        base_image: cloudfoundry/build:full
        squash: squash
    attempts: 2
- name: update-bionic-build-base-image
  public: true
  plan:
  - get: bionic-build-base-dockerfile
    trigger: true
  - put: bionic-build-base-image
    params:
      build: bionic-build-base-dockerfile/bionic/base/build
      build_args:
        squash: squash
      attempts: 2
- name: update-bionic-build-cnb-image
  public: true
  plan:
  - get: bionic-build-cnb-dockerfile
    trigger: true"
  - get: bionic-build-base-image
    trigger: true
    passed:
    - update-bionic-build-base-image
  - put: bionic-build-cnb-image
    params:
      build: bionic-build-cnb-dockerfile/bionic/cnb/build
      build_args:
        base_image: cloudfoundry/build:base
        squash: squash
      attempts: 2
      tag_as_latest: true
